export const ProfileActionTypes = {
    'UPDATE_PROFILE': 'UPDATE_PROFILE',
    'UPDATE_LOADER': 'UPDATE_LOADER',
    'UPDATE_PROFILE_SUCCESS': 'UPDATE_PROFILE_SUCCESS',
    'UPDATE_PROFILE_FAILURE': 'UPDATE_PROFILE_FAILURE',
    'UPDATE_PASSWORD': 'UPDATE_PASSWORD',
    'UPDATE_PASSWORD_SUCCESS': 'UPDATE_PASSWORD_SUCCESS',
    'UPDATE_PASSWORD_FAILURE': 'UPDATE_PASSWORD_FAILURE',
    'RESET_MESSAGE': 'RESET_MESSAGE',
    'FORM_ERROR': 'FORM_ERROR',
}