const SectionActionTypes = {
  FETCH_SECTION_DATA: 'FETCH_SECTION_DATA',
  FETCH_SECTION_DATA_SUCCESS: 'FETCH_SECTION_DATA_SUCCESS',
  FETCH_SECTION_DATA_ERROR: 'FETCH_SECTION_DATA_ERROR',
};

export default SectionActionTypes;