const CourseActionTypes = {
  FETCH_COURSE_DATA: 'FETCH_COURSE_DATA',
  FETCH_COURSE_IN_PROGRESS_DATA: 'FETCH_COURSE_IN_PROGRESS_DATA',
  FETCH_COURSE_COMPL_DATA: 'FETCH_COURSE_COMPL_DATA',
  FETCH_COURSE_DATA_SUCCESS: 'FETCH_COURSE_DATA_SUCCESS',
  FETCH_COURSE_IN_PROGRESS_DATA_SUCCESS: 'FETCH_COURSE_IN_PROGRESS_DATA_SUCCESS',
  FETCH_COURSE_COMPL_DATA_SUCCESS: 'FETCH_COURSE_COMPL_DATA_SUCCESS',
  FETCH_COURSE_DATA_ERROR: 'FETCH_COURSE_DATA_ERROR',
  UPDATE_USER_COURSE: 'UPDATE_USER_COURSE',
  UPDATE_TIME_SPENT: 'UPDATE_TIME_SPENT',
  UPDATE_TIME_SPENT_ERROR: 'UPDATE_TIME_SPENT_ERROR',
};

export default CourseActionTypes;