export const UserActionTypes = {
    'SET_CURRENT_USER': 'SET_CURRENT_USER',
    'AUTH_USER': 'AUTH_USER',
    'AUTH_USER_SUCCESS': 'AUTH_USER_SUCCESS',
    'AUTH_USER_FAILURE': 'AUTH_USER_FAILURE',
    'SIGN_USER': 'SIGN_USER',
    'SIGN_USER_SUCCESS': 'SIGN_USER_SUCCESS',
    'SIGN_USER_FAILURE': 'SIGN_USER_FAILURE'
}